### ISSUE TITLE
Set_speed

### ISSUE THREAD

**Issue by hollapm** [quielb/hass-airscape#10]
The set_speed settings have changed. I use to use speed 1,2,...10 and these no longer work. It appears it only takes low, medium and high.
Is there a way to revert this back or correct the speeds?
Thanks

**Comment by quielb** [comment]
What version of HA are you running? This integration was updated to support the new speed model for fans introduced in HA version 2021.3. Legacy support for fan speeds was not maintained in this integration.

**Comment by hollapm** [comment]
I'm using version 2021.6.2
The only states I am seeing for fan speed are:
speed_list:
  - 'off'
  - low
  - medium
  - high

previously I could set the speed with set_speed "1,2,...,10" which I used, but am now getting an API error.
instead of set_speed do I need to do set_percentage? then set percentage to the speed (IE speed 3 = 30?)

**Comment by quielb** [comment]
The speed_list that you see is because the base FanEntity still has legacy support for the old fan model. You did answer your own question, you need to use set_percentage instead of set_speed. But the percentage should be based on the number of speeds for your particular fan, if dynamic speed "detection" is working properly. In the UI if you click on the fan and move the speed slider it should snap to the available percentages. Since your fan is only 2 speed, you should only have 50% and 100% speeds.

**Comment by hollapm** [comment]
I'll take a look at this. I have one of the 10 speed fans so believe it will be 10, 20, 30,..., 100
